set_property SRC_FILE_INFO {cfile:C:/Users/ivr/Documents/GitHub/Zybo_OV7670/Ps_CommunicateWithAXI_Lchika/Ps_CommunicateWithAXI_Lchika.srcs/constrs_1/new/AXILchika.xdc rfile:../../../Ps_CommunicateWithAXI_Lchika.srcs/constrs_1/new/AXILchika.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:5 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN D18 [get_ports {MY_OUT_0[3]}]
set_property src_info {type:XDC file:1 line:6 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN G14 [get_ports {MY_OUT_0[2]}]
set_property src_info {type:XDC file:1 line:7 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN M15 [get_ports {MY_OUT_0[1]}]
set_property src_info {type:XDC file:1 line:8 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN M14 [get_ports {MY_OUT_0[0]}]
